theme: jekyll-theme-cayman

title: Out-of-distribution generalization and adaptation <br>in natural and artificial intelligence
description: NeurIPS 2021 Workshop

timezone: America/New_York

navigation:
  Home: "index"
  Invited Speakers: "speakers"
  Organizers: "organizers"
  Schedule: "schedule"
  Programme Committee: "committee"
  FAQ: "faq"
  Submit Questions: "question"
# navigation:
#   - title: Home
#     url: /index.html
#   - title: Invited Speakers
#     url: /speakers.html
#     sublinks:
#       - title: Continual
#         url: /continual
#       - title: Causal
#         url: /causal
#       - title: separator
#       - title: Compositional
#         url: /compositional
#   - title: Organizers
#     url: /organizers
#   - title: Programme Committee
#     url: /committee
#   - title: FAQ
#     url: /faq
#   - title: Submit Questions
#     url: /question

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ["README.md", "Gemfile", "Gemfile.lock"]
